### ISSUE TITLE
Do you have original dataset having text?

### ISSUE THREAD

**Issue by TianlinZhang668** [MatthewMatero/AffectiveLanguageForecasting#1]
Do you have original dataset having text? Could you please provide them? Thank you

**Comment by MatthewMatero** [comment]
Hi, Thanks for showing interest in the dataset. 

Unfortunately, I cannot share the raw tweets for privacy concerns. The dataset files here have the tweet ids which can be used to download (via a twitter api) any tweets that are still available (i.e. those not deleted by the user). I hope this was helpful.
